/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/desktop/bookshelf/': RouteRecordInfo<'/desktop/bookshelf/', '/desktop/bookshelf', Record<never, never>, Record<never, never>>,
    '/desktop/bookstore/': RouteRecordInfo<'/desktop/bookstore/', '/desktop/bookstore', Record<never, never>, Record<never, never>>,
    '/desktop/setting/': RouteRecordInfo<'/desktop/setting/', '/desktop/setting', Record<never, never>, Record<never, never>>,
    '/mobile/bookshelf/': RouteRecordInfo<'/mobile/bookshelf/', '/mobile/bookshelf', Record<never, never>, Record<never, never>>,
    '/mobile/bookstore/': RouteRecordInfo<'/mobile/bookstore/', '/mobile/bookstore', Record<never, never>, Record<never, never>>,
    '/mobile/setting/': RouteRecordInfo<'/mobile/setting/', '/mobile/setting', Record<never, never>, Record<never, never>>,
  }
}
